services:
  mongodb:
    build:
      context: ./1-mongodb
      dockerfile: Dockerfile #it moves to the current directory
    image: mongodb # docker build -t mongodb
    container_name: mongodb

  cart:
    build: 
      context: ./5-cart
      dockerfile: Dockerfile
    image: cart
    container_name: cart
    depends_on:
      - redis
      - catalogue


  mysql:
    build: 
      context: ./6-mysql
      dockerfile: Dockerfile
    image: mysql
    container_name: mysql


  shipping:
    build: 
      context: ./7-shipping
      dockerfile: Dockerfile
    image: shipping
    container_name: shipping
    depends_on:
    - mysql
    - cart


  payment:
    build: 
      context: ./8-payment
      dockerfile: Dockerfile
    image: payment
    container_name: payment
    container_: payment
    depends_on:
    - rabbitmq
    - cart
    - user
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_USER: "roboshop"
      AMQP_PASSWORD: "roboshop123"

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
      container_name: rabbitmq


     


  user:
    build:
      context: ./4-user
      dockerfile: Dockerfile
    image: user
    container_name: user
    depends_on:
      - redis
      - mongodb

  frontend:
    build: 
      context: ./3-frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    depends_on:
      - catalogue
      - user
      - cart
      - payment
      - shipping
    ports:
      - "80:80"


  redis:
    image: redis:7.0
    container_name: redis

  catalogue:
    build: 
      context: ./2-catalogue
      dockerfile: Dockerfile
    image: catalogue 
    container_name: catalogue
    depends_on:
      - mongodb

networks:
  default:
    driver: bridge
    name: rakesh
    external: false # true means  u need to create it maually, but false means it will create 
