services:
  mongodb:
    build:
      context: ./1-mongodb
      dockerfile: Dockerfile #it moves to the current directory
    image: mongodb # docker build -t mongodb
    container_name: mongodb

  cart:
    build: 
      context: ./5-cart
      dockerfile: Dockerfile
    image: cart
    container_name: cart
    depends_on:
      - redis


  mysql:
    build: 
      context: ./6-mysql
      dockerfile: Dockerfile
    image: mysql
    container_name: mysql
    
     


  user:
    build:
      context: ./4-user
      dockerfile: Dockerfile
    image: user
    container_name: user
    depends_on:
      - redis

  frontend:
    build: 
      context: ./3-frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    depends_on:
      - catalogue
      - user
      - cart
    ports:
      - "80:80"


  redis:
    image: redis:7.0
    container_name: redis

  catalogue:
    build: 
      context: ./2-catalogue
      dockerfile: Dockerfile
    image: catalogue 
    container_name: catalogue
    depends_on:
      - mongodb

networks:
  default:
    driver: bridge
    name: rakesh
    external: false # true means  u need to create it maually, but false means it will create 
